version: 2

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    steps:
      - checkout
      - restore_cache:
          keys:
            - my_cache

      # google drive link to test data, thanks to Gael V. and Chris G.
      # https://googledrive.com/host/0B2JWN60ZLkgkMEw4bW5VUUpSdFU/ds005-deriv-light.tar
      - run: if [[ ! -d ~/data/ds005-deriv-light/derivatives ]]; then wget -c -P ${HOME}/downloads/ -O ds005-deriv-light.tar "https://storage.googleapis.com/cos-osf-prod-files-us/7617a7b295f06319a3c05187656f985456ff546dffa2c9dffedf13ee1d292df1?response-content-disposition=attachment%3B%20filename%3D%22ds005-deriv-light.tar%22%3B%20filename%2A%3DUTF-8%27%27ds005-deriv-light.tar&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1672597819&Signature=NLd5G7qorwMTrYqLqRRnftkyZ3Mq%2B50sW%2FE0Rwd1aSeERPkEoA0xJ2bH2vyemKM7v%2BBHXhLpBEB3%2BCFQmpB1oqTjd7uplppJBrxdyXVuY9EdpfhMsB6eorB4rkJuk1k6XS14EpP%2BvmGMMxrGCBVwQfUJZnJRHEk8guPBISJE3aeYgF2WtLnHWplWK4iHbn4JAhk2qNzQyY7rMgoeH0FWIWbzV%2Bgs6Y4Zw1gVOiGSk2lPQTrWI2yxbJFIoqT0T%2FVeYLthR%2BngNFQg6WfJoNZPapqlsnJpYI4rIwGxW7BLyNss2xZNAkQ4vkGNlv9IUfoGzCigcrIOjz5sIIX8NnG%2Bsw%3D%3D" && mkdir -p ${HOME}/data && tar xf ${HOME}/downloads/ds005-deriv-light.tar -C ${HOME}/data; fi
      - run: git describe --tags --always > version
      - run:
          command: docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          no_output_timeout: 6h
      - run: mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
      - run: mkdir -p ${HOME}/outputs

      - run:
          command: docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01
          no_output_timeout: 6h
      - run:
          command: docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 02
          no_output_timeout: 6h
      - run:
          command: docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 03
          no_output_timeout: 6h
      - run:
          command: docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group
          no_output_timeout: 6h


      - save_cache:
          key: my_cache
          paths:
            - "~/docker"
            - "~/data"

  deployment:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/image.tar
      - run:
          command: if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME}:latest; fi
          no_output_timeout: 6h
      - run:
          command: if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME} bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG; fi
          no_output_timeout: 6h

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deployment:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

# VS Code Extension Version: 1.5.1
